name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"
      - "!frontend/README.md"

jobs:
  deploy:
    if: vars.DEPLOY_FRONTEND == 'true'
    runs-on: ubuntu-24.04-arm

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          version: ">=10.0.0"

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-deploy-devops-profile-coffee-card-app-demo
          aws-region: ap-southeast-2

      - name: Get CloudFront distribution details
        id: cloudfront
        run: |
          read -r CD_DIST_ID CF_DIST_DOMAIN_NAME <<< "$(aws cloudfront list-distributions \
            --query "DistributionList.Items[?Origins.Items[?contains(DomainName, 'coffee-card-frontend-prod')]] | [0].[Id, DomainName]" \
            --output text)"

          echo "CD_DIST_ID=$CD_DIST_ID" >> "$GITHUB_OUTPUT"
          echo "CF_DIST_DOMAIN_NAME=$CF_DIST_DOMAIN_NAME" >> "$GITHUB_OUTPUT"

      - name: Build
        env:
          VITE_API_BASE_URL: https://${{ steps.cloudfront.outputs.CF_DIST_DOMAIN_NAME }}
        run: pnpm build

      - name: Sync to S3
        run: |
          aws s3 sync dist/ "s3://coffee-card-frontend-prod" --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ steps.cloudfront.outputs.CD_DIST_ID }}" \
            --paths "/*"